### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by kenu**
Fixed a few typos in `README.md`

### CODE REVIEW

**Review by hornetmj — APPROVED** [review]

**Comment by hornetmj** [comment]
@swi0110 Aren't you the manager of this repository? This PR is for fixing a typo from the manager of the 'Innovation Academy' who works with our team. So, I just merge it without notifying and sharing it. Please, let me know if there is any problem.

**Comment by hornetmj** [comment]
@kenu We have a process of a developer. Please read the following link if you want to contribute our code. It seems good to us to follow the process after this Pull Request.
- https://dev.cubrid.org/dev-process

**Comment by kenu** [comment]
@hornetmj
Hello, As you told that I am a mentor of Innovation Academy.
I found a few typos while preparing the study.
So I sent PR for this docker related repo.

Thank you for accepting my proposal.

**Comment by swi0110** [comment]
@kenu 
The develop branch was not maintained.
It maybe would not build on docker.
you can use the master branch.

**Comment by kenu** [comment]
@swi0110 Thank you for your guide!

**Pull request merged**
